version: "3.8"
services:
  backend:
    restart: always
    build:
      context: ./
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - $PWD/backend/app:/backend/app
    environment:
      - DATASET_PATH=/backend/dataset.df.pickle

  frontend:
    restart: always
    build: frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - $PWD/frontend/:/frontend/
    environment:
      - REACT_APP_URL=backend://backend:8080
